# Woodpecker CI Pipeline for Domain Expiry Tracker
# Triggers on push to main branch

when:
  branch: main
  event: push

# Pipeline steps run sequentially by default
steps:
  # Step 1: Build Docker image
  - name: build
    image: docker:27-dind
    privileged: true
    commands:
      - sleep 5 # Wait for Docker daemon to start
      - docker build -t 192.168.4.162:5000/domain-expiry-tracker:${CI_COMMIT_SHA} .
      - docker tag 192.168.4.162:5000/domain-expiry-tracker:${CI_COMMIT_SHA} 192.168.4.162:5000/domain-expiry-tracker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Step 2: Push to registry
  - name: push
    image: docker:27-dind
    privileged: true
    commands:
      - docker push 192.168.4.162:5000/domain-expiry-tracker:${CI_COMMIT_SHA}
      - docker push 192.168.4.162:5000/domain-expiry-tracker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - build

  # Step 3: Deploy to Kubernetes
  - name: deploy
    image: bitnami/kubectl:1.31
    commands:
      - kubectl set image deployment/domain-tracker domain-tracker=192.168.4.162:5000/domain-expiry-tracker:${CI_COMMIT_SHA} -n domain-tracker
      - kubectl rollout status deployment/domain-tracker -n domain-tracker --timeout=120s
    depends_on:
      - push
