# Woodpecker CI Pipeline for Domain Expiry Tracker
# Triggers on push to main branch
# Uses Kaniko for unprivileged Docker builds

when:
  branch: main
  event: push

steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:debug
    volumes:
      - name: workspace
        emptyDir: {}
    commands:
      - /kaniko/executor
        --context .
        --dockerfile Dockerfile
        --destination 192.168.4.162:5000/domain-expiry-tracker:${CI_COMMIT_SHA}
        --destination 192.168.4.162:5000/domain-expiry-tracker:latest
        --insecure

  - name: deploy
    image: bitnami/kubectl:1.31
    volumes:
      - name: workspace
        emptyDir: {}
    commands:
      - kubectl set image deployment/domain-tracker domain-tracker=192.168.4.162:5000/domain-expiry-tracker:${CI_COMMIT_SHA} -n domain-tracker
      - kubectl rollout status deployment/domain-tracker -n domain-tracker --timeout=120s
