name: Build and Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: 192.168.4.162:5000
  IMAGE_NAME: domain-expiry-tracker
  NAMESPACE: domain-tracker

jobs:
  build:
    runs-on: host
    steps:
      - name: Checkout
        run: |
          rm -rf /tmp/domain-expiry-tracker
          git clone http://git.digitaladrenalin.net/Shared-workspace/domain-expiry-tracker.git /tmp/domain-expiry-tracker
          cd /tmp/domain-expiry-tracker
          git checkout ${{ github.sha }}

      - name: Build and push
        run: |
          cd /tmp/domain-expiry-tracker
          IMAGE_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          LATEST_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
          docker build -t $IMAGE_TAG -t $LATEST_TAG .
          docker push $IMAGE_TAG
          docker push $LATEST_TAG

  deploy:
    runs-on: host
    needs: build
    steps:
      - name: Checkout
        run: |
          rm -rf /tmp/domain-expiry-tracker
          git clone http://git.digitaladrenalin.net/Shared-workspace/domain-expiry-tracker.git /tmp/domain-expiry-tracker
          cd /tmp/domain-expiry-tracker
          git checkout ${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          cd /tmp/domain-expiry-tracker
          # Create namespace if it doesn't exist
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          
          # Apply k8s manifests
          kubectl apply -k k8s/
          
          # Update deployment with new image
          IMAGE_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          kubectl set image deployment/domain-tracker domain-tracker=$IMAGE_TAG -n ${{ env.NAMESPACE }}
          
          # Wait for rollout
          kubectl rollout status deployment/domain-tracker -n ${{ env.NAMESPACE }} --timeout=120s

      - name: Verify deployment
        run: |
          kubectl get pods -n ${{ env.NAMESPACE }}
          kubectl get svc -n ${{ env.NAMESPACE }}
